name: Build and Push Docker Image On Release

on:
  push:
    branches:
      - 'develop'
      - 'main'

    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
    REGISTRY_ROOT: ghcr.io
    

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host


      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: 'device-management-service'

      - name: Checkout dependent rdkcentral/rdk_logger repository
        uses: actions/checkout@v4
        with:
          repository: 'rdkcentral/rdk_logger'
          ref: 'IMPORT_INITIAL_develop'
          path: 'device-management-service/native-platform/rdk_logger'

      - name: Check out the dependent rdkcentral/webconfigframework repository
        uses: actions/checkout@v4
        with:
          repository: 'rdkcentral/WebconfigFramework'
          ref: 'IMPORT_INITIAL_develop'
          path: 'device-management-service/native-platform/WebconfigFramework'

      - name: Check out the dependent rdkcentral/libSyscallWrapper repository
        uses: actions/checkout@v4
        with:
          repository: 'rdkcentral/libSyscallWrapper'
          ref: 'IMPORT_INITIAL_develop'
          path: 'device-management-service/native-platform/libSyscallWrapper'
  
      - name: Check out the dependent rdkcentral/common_utilities repository
        uses: actions/checkout@v4
        with:
          repository: 'rdkcentral/common_utilities'
          ref: '1.2.0'
          path: 'device-management-service/native-platform/common_utilities'

      - name: Check out the dependent rdkcentral/tr69hostif repository
        uses: actions/checkout@v4
        with:
          repository: 'rdkcentral/tr69hostif'
          ref: '1.1.3'
          path: 'device-management-service/native-platform/tr69hostif'

      - name: Log in to enterprise registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_ROOT }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push mock xconf image
        uses: docker/build-push-action@v4
        with:
          context: device-management-service/mock-xconf
          platforms: linux/amd64
          push: true
          tags: |
            ${{  env.REGISTRY_ROOT }}/${{ github.repository }}/mockxconf:${{ github.ref_name }}
          load: false

      - name: Dump certificate from mock-xconf container
        run: |
          docker run --rm ${{  env.REGISTRY_ROOT }}/${{ github.repository }}/mockxconf:latest cat /etc/xconf/certs/mock-xconf-server-cert.pem > device-management-service/native-platform/mock-xconf-server-cert.pem
       
      - name: Build and push native-platform image
        uses: docker/build-push-action@v4
        with:
          context: device-management-service/native-platform        
          platforms: linux/amd64
          build-args: |
            - REVISION=${{ github.ref_name }}
          push: true
          tags: |
            ${{  env.REGISTRY_ROOT }}/${{ github.repository }}/native-platform:${{ github.ref_name }}
          load: false
       
   
      - name: Clean up
        run: |
          rm -f mock-xconf-server-cert.pem
          rm -rf rdk_logger
          rm -rf WebconfigFramework
        
