name: Verify building of test containers

on:
  pull_request:
    branches: [ "develop" ]

env:
    REGISTRY_ROOT: ghcr.io
    

jobs:
  build-only:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout docker config repository
        uses: actions/checkout@v4
        with:
          path: 'device-management-service'

      - name: Checkout dependent rdkcentral/rdk_logger repository
        uses: actions/checkout@v4
        with:
          repository: 'rdkcentral/rdk_logger'
          ref: 'IMPORT_INITIAL_develop'
          path: 'device-management-service/native-platform/rdk_logger'

      - name: Check out the dependent rdkcentral/webconfigframework repository
        uses: actions/checkout@v4
        with:
          repository: 'rdkcentral/WebconfigFramework'
          ref: 'IMPORT_INITIAL_develop'
          path: 'device-management-service/native-platform/WebconfigFramework'

      - name: Check out the dependent rdkcentral/libSyscallWrapper repository
        uses: actions/checkout@v4
        with:
          repository: 'rdkcentral/libSyscallWrapper'
          ref: 'IMPORT_INITIAL_develop'
          path: 'device-management-service/native-platform/libSyscallWrapper'

      - name: Check out the dependent rdkcentral/common_utilities repository
        uses: actions/checkout@v4
        with:
            repository: 'rdkcentral/common_utilities'
            ref: '1.1.0'
            path: 'device-management-service/native-platform/common_utilities'

      - name: Check out the dependent rdkcentral/tr69hostif repository
        uses: actions/checkout@v4
        with:
          repository: 'rdkcentral/tr69hostif'
          ref: '1.0.11'
          path: 'device-management-service/native-platform/tr69hostif'
       
      - name: Build mock xconf image
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          context: device-management-service/mock-xconf
          push: true
          tags: localhost:5000/mockxconf:latest
          load: false

      - name: Dump self-signed public serts from mock-xconf container
        run: |
          docker run --rm localhost:5000/mockxconf:latest cat /etc/xconf/certs/mock-xconf-server-cert.pem >  device-management-service/native-platform/mock-xconf-server-cert.pem

      - name: Build native-platform image
        uses: docker/build-push-action@v4
        with:
          context: device-management-service/native-platform
          platforms: linux/amd64
          build-args: |
            - REVISION=${{ github.ref_name }}
          push: false
          tags: native-platform:latest
          load: false

      - name: Prepare expected directory for mount in docker-compose
        run: |
          mkdir -p /tmp/L2_CONTAINER_SHARED_VOLUME

        
